spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.11:8849
    gateway:
      routes:
        - id: route1
          uri: https://github.com/
          predicates:
            - Query=web,git
        - id: route2
          uri: https://bilibili.com/
          predicates:
            - Query=web,bilibili
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}

server:
  port: 8070

# routing